### PR TITLE
Add IP address functions

### PR DESCRIPTION
**Pull request by mattdurant**
## Description

Adding functions for working with IP addresses:

- ipv4_in_subnet
- ipv6_in_subnet
- ipv4_is_public
- ipv6_is_public

## Related Tickets & Documents

N/A

## Screenshots/Recordings

N/A

## Steps to QA

Use the functions in a workflow with known values

### CODE REVIEW

**Review by daryllimyt — APPROVED** [review]
LGTM

**Comment by mattdurant** [comment]
@topher-lo added unit tests for all 4 IP functions

**Review by topher-lo — APPROVED** [review]

**Comment by mattdurant** [comment]
@daryllimyt That should do it, looks like a collision between those last 2 PRs I did that modified the same 2 files in the same areas.

**Review by daryllimyt — APPROVED** [review]
LGTM, just need linter passing

**Comment by mattdurant** [comment]
@daryllimyt fixed

**Comment by daryllimyt** [comment]
unsure why the linter keeps failing here...

**Comment by mattdurant** [comment]
@daryllimyt OK, should pass now

**Pull request merged**
