### PR TITLE
feat(integration): Add list crowdstrike detections summary

### PR DESCRIPTION
**Pull request by benacumen**
Added a new integration which can fetch detection details by passing in the detection IDs.

## Description

When querying for CrowdStrike detections, an array of detection IDs are returned. Currently, there is no integration which allows you to use these IDs and query for detection details. This integration simply takes the array of IDs and returns the full detection details.

## Screenshots/Recordings

Sample Use Case:
image

Sample Configuration:
image

## Steps to QA

1. Verify the code is valid
2. Create a workflow using the List CrowdStrike Detects and the new Get CrowdStrike Detect Summaries integrations
3. Validate that an array of detection details is returned

### CODE REVIEW

**Comment by topher-lo** [comment]
Thanks for opening this PR! Please request a review @benacumen and we can get this into Tuesday's 0.9.0 release 👍

**Comment by benacumen** [comment]
> Thanks for opening this PR! Please request a review @benacumen and we can get this into Tuesday's 0.9.0 release 👍

image

I don't appear to be able to request a review @topher-lo, am I being dumb?

**Comment by topher-lo** [comment]
> I don't appear to be able to request a review @topher-lo, am I being dumb?

Let me look into the review request, it might be that you must have contributed at least one PR in the past to self-request a review.

But one quick comment, your PR is currently failing linting. Have you setup pre-commit yet? https://pre-commit.com/ You'll have to run `ruff` again on the crowdstrike file to reformat the file

**Comment by benacumen** [comment]
> > I don't appear to be able to request a review @topher-lo, am I being dumb?
> 
> Let me look into the review request, it might be that you must have contributed at least one PR in the past to self-request a review.
> 
> But one quick comment, your PR is currently failing linting. Have you setup pre-commit yet? https://pre-commit.com/ You'll have to run `ruff` again on the crowdstrike file to reformat the file

Okay, I believe I've fixed this in the latest commit. I'll keep any eye out for further failures

**Pull request merged**
